# SP²B2: Extract all inproceedings with properties `dc:creator',
# `bench:booktitle', `dcterms:issued', `dcterms:partOf',
# `rdfs:seeAlso', `dc:title', `swrc:pages', `foaf:homepage', and
# optionally `bench:abstract', including their values.
#
# This query implements a bushy graph pattern.  It contains a single,
# simple `optional' expression, and accesses large strings (i.e. the
# abstracts).  Result size grows with database size, and a final
# result ordering is necessary due to operator `order by'.  Both
# native and in-memory engines might reach evaluation times that are
# almost linear to the document size.
#
# |     10,000 |       147 |
# |     50,000 |       965 |
# |    250,000 |     6,197 |
# |  1,000,000 |    32,770 |
# |  5,000,000 |   248,738 |
# | 25,000,000 | 1,876,999 |
#
# O(n)

prefix bench: <http://localhost/vocabulary/bench/>
prefix    dc: <http://purl.org/dc/elements/1.1/>
prefix   dct: <http://purl.org/dc/terms/>
prefix  foaf: <http://xmlns.com/foaf/0.1/>
prefix  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix  swrc: <http://swrc.ontoware.org/ontology#>
select ?inproc ?author ?booktitle ?title ?proc ?ee ?page ?url ?yr ?abstract {
  ?inproc a bench:Inproceedings ;
    dc:creator ?author ;
    bench:booktitle ?booktitle ;
    dc:title ?title ;
    dct:partOf ?proc ;
    rdfs:seeAlso ?ee ;
    swrc:pages ?page ;
    foaf:homepage ?url ;
    dct:issued ?yr
  optional {
    ?inproc bench:abstract ?abstract
  }
}
order by ?yr
