# SP²B5b: Return the names of all persons that occur as author of at
# least one inproceeding and at least one article.
#
# This query explicitly joins the authors on variable name.  The
# one-to-one mapping between authors and their names (i.e. author
# names constitute primary keys) in our scenario implies equivalence
# with query SP²B5a.  In [14], semantic optimization on top of such
# keys for RDF has been proposed.  Such an approach might detect the
# equivalence of both queries in this scenario and select the more
# efficient variant.
#
# |     10,000 |     155 |
# |     50,000 |   1,085 |
# |    250,000 |   6,904 |
# |  1,000,000 |  35,241 |
# |  5,000,000 | 210,662 |
# | 25,000,000 | 696,681 |

prefix bench: <http://localhost/vocabulary/bench/>
prefix    dc: <http://purl.org/dc/elements/1.1/>
prefix  foaf: <http://xmlns.com/foaf/0.1/>
select distinct ?person ?name {
  ?article a bench:Article ;
    dc:creator ?person .
  ?inproc a bench:Inproceedings ;
    dc:creator ?person .
  ?person foaf:name ?name
}
