prefix bag: <http://bag.basisregistraties.overheid.nl/def/bag#>
prefix beeldbank: <https://cultureelerfgoed.nl/vocab/>
prefix dbo: <http://dbpedia.org/ontology/>
prefix dct: <http://purl.org/dc/terms/>
prefix energie: <http://data.labs.pdok.nl/dataset/energie#>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix gemeente: <https://data.pdok.nl/cbs/id/gemeente/>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix graph: <https://data.labs.pdok.nl/graph/>
prefix kvk: <http://data.labs.pdok.nl/dataset/bedrijf#>
prefix monumenten: <http://lod.kb.nl/rce/vocab/id/01/ceo#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix schema: <http://schema.org/>
prefix vcard: <http://www.w3.org/2006/vcard/ns#>
prefix labs: <https://data.labs.pdok.nl/bag/def/>
select ?shape ?shapeColor ?shapeHeight ?shapeName (sample(?shapeLabel) as ?shapeLabel)  {
  {
select * {
    values (?woonplaatsNaam ?straatNaam) { ("Apeldoorn" "Molenstraat-Centrum") }
    ?openbareRuimte bag:naamOpenbareRuimte ?straatNaam;
                    bag:bijbehorendeWoonplaats ?woonplaats.
    ?woonplaats bag:naamWoonplaats ?woonplaatsNaam.
    ?nummeraanduiding bag:bijbehorendeOpenbareRuimte ?openbareRuimte;
                      bag:huisnummer ?huisnummer;
                      bag:postcode ?postcode.
    ?verblijfsobject bag:hoofdadres ?nummeraanduiding;
                     bag:oppervlakte ?oppervlakte;
                     bag:pandrelatering ?pand;
                     bag:status ?verblijfsobjectStatus.
    ?verblijfsobjectStatus rdfs:label ?verblijfsobjectStatusLabel.
    ?pand geo:hasGeometry/geo:asWKT ?shape;
          bag:oorspronkelijkBouwjaar ?bouwjaar;
          bag:status ?pandStatus.
    ?pandStatus rdfs:label ?pandStatusLabel.

    }
  }

   service <https://data.labs.pdok.nl/sparql>	{
     ?pand labs:measuredHeight ?shapeHeight.
   }

   BIND(IF(!bound(?EindGeldigheid5) &&!bound(?EindGeldigheid4) &&!bound(?EindGeldigheid3) &&!bound(?EindGeldigheid2) &&!bound(?EindGeldigheid1), "#22b14c", "#ed1c24" ) AS ?pandWktColor)
BIND(IF(!bound(?EindGeldigheid5) &&!bound(?EindGeldigheid4) &&!bound(?EindGeldigheid3) &&!bound(?EindGeldigheid2) &&!bound(?EindGeldigheid1), ?Height, 0) AS ?pandWktHeight)

  bind(concat('<h4>',str(?straatNaam),' ',str(?huisnummer),', ',str(?postcode),' ',str(?woonplaatsNaam),'</h4><h5><a href="',str(?verblijfsobject),'" target="_blank">Verblijfsobject</a>:</h5><ul><li>Woonplaats: <a href="',str(?woonplaats),'" target="_blank">',str(?woonplaatsNaam),'</a></li><li>Oppervlakte: ',replace(str(?oppervlakte),'[0-9](?=(?:[0-9]{3})+(?![0-9]))','$0.'),' m²</li><li>Status: <a href="',str(?verblijfsobjectStatus),'" target="_blank">',str(?verblijfsobjectStatusLabel),'</a></li></ul><h5><a href="',str(?pand),'" target="_blank">Pand</a>:</h5><ul><li>Bouwjaar: ',str(?bouwjaar),'</li><li>Status: <a href="',str(?pandStatus),'" target="_blank">',str(?pandStatusLabel),'</a></li></ul>') as ?shapeLabel)
  # tekst label
  bind(concat(str(?straatNaam),' ',str(?huisnummer),', ',str(?woonplaatsNaam)) as ?shapeName)
}
group by ?shape ?shapeColor ?shapeHeight ?shapeName
limit 250
