PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX au: <http://inspire.ec.europa.eu/ont/au#>
PREFIX nationallevel: <http://inspire.ec.europa.eu/codelist/AdministrativeHierarchyLevel/>
PREFIX inspire: <http://inspire.ec.europa.eu/codelist/AdministrativeHierarchyLevel/>

SELECT
?country
(count(distinct ?au1st) as ?1stLevel)
(count(distinct ?au2nd) as ?2ndLevel)
(count(distinct ?au3rd) as ?3rdLevel)
(count(distinct ?au4th) as ?4thLevel)

WHERE {
  {
    VALUES (?g ?country) {(<http://data.labs.pdok.nl/dataset/openels/au> "The Netherlands")}
    GRAPH ?g {
      ?au1st au:AdministrativeUnit.nationalLevel inspire:1stOrder.
      ?au2nd au:AdministrativeUnit.nationalLevel inspire:2ndOrder.
      ?au3rd au:AdministrativeUnit.nationalLevel inspire:3rdOrder.
    }
  }
  UNION {
    SERVICE <http://193.167.189.160/openels/fuseki/ds/query> {
      VALUES (?g ?country) {(<http://paikkatiedot.fi/ds/openels/au> "Finland")}
      GRAPH ?g {
      ?au1st au:AdministrativeUnit.nationalLevel inspire:1stOrder.
      ?au2nd au:AdministrativeUnit.nationalLevel inspire:2ndOrder.
      ?au4th au:AdministrativeUnit.nationalLevel inspire:4thOrder.
        OPTIONAL {?au3rd au:AdministrativeUnit.nationalLevel inspire:3rdOrder.}
      }
    }
  }
  UNION {
    SERVICE <http://rdf.kartverket.no//sparql> {
      VALUES (?g ?country) {(<http://openels/administrativeunits> "Norway")}
      GRAPH ?g {
      ?au1st au:AdministrativeUnit.nationalLevel inspire:1stOrder.
      ?au2nd au:AdministrativeUnit.nationalLevel inspire:2ndOrder.
      ?au3rd au:AdministrativeUnit.nationalLevel inspire:3rdOrder.
      }
    }
  }
}
GROUP BY ?g ?country
