prefix schema: <http://schema.org/>
select * {
  service <http://data.bibliotheken.nl/sparql> {
    ?book a schema:Book .
    ?book schema:name ?title .
    ?book schema:about <http://data.bibliotheken.nl/id/thes/p075601230> . #bier
  }
}
