prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rvo: <https://data.labs.pdok.nl/rvo/def/>
select ?shape ?shapeLabel {
  ?land a rvo:Land;
    owl:sameAs/geo:hasGeometry/geo:asWKT ?shape;
    rdfs:label ?naam;
    rvo:vlag ?url.
  bind(concat("<h2>",?naam,'</h2></a>',
    '<img src="',?url,'" width="300">') as ?shapeLabel)
}
