prefix bag: <http://bag.basisregistraties.overheid.nl/def/bag#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select ?pandWkt ?pandWktLabel {
  values (?woonplaatsNaam ?straatNaam ?huisnummer) {
    ("Warnsveld" "'t Spiker" 24)
  }
  ?openbareRuimte bag:bijbehorendeWoonplaats ?woonplaats ;
                  bag:naamOpenbareRuimte ?straatNaam .
  ?woonplaats bag:naamWoonplaats ?woonplaatsNaam .
  ?nummeraanduiding bag:bijbehorendeOpenbareRuimte ?openbareRuimte ;
                    bag:huisnummer ?huisnummer .
  ?verblijfsobject bag:hoofdadres ?nummeraanduiding ;
                   bag:oppervlakte ?oppervlakte ;
                   bag:pandrelatering ?pand ;
                   bag:status ?verblijfsobjectStatus .
  ?verblijfsobjectStatus rdfs:label ?verblijfsobjectStatusLabel .
  ?pand bag:geometriePand/geo:asWKT ?pandWkt ;
        bag:oorspronkelijkBouwjaar ?bouwjaar ;
        bag:status ?pandStatus .
  ?pandStatus rdfs:label ?pandStatusLabel
  bind (concat(
    '<h4>',str(?straatNaam),' ',str(?huisnummer),'</h4>',
    '<h5><a href="',str(?verblijfsobject),'">Verblijfsobject</a>:</h5>',
    '<ul><li>Woonplaats: <a href="',str(?woonplaats),'">',str(?woonplaatsNaam),'</a></li>',
    '<li>Oppervlakte: ',str(?oppervlakte),'m²</li>',
    '<li>Status: <a href="',str(?verblijfsobjectStatus),'">',str(?verblijfsobjectStatusLabel),'</a></li></ul>',
    '<h5><a href="',str(?pand),'">Pand</a>:</h5>',
    '<ul><li>Bouwjaar: ',str(?bouwjaar),'</li>',
    '<li>Status: <a href="',str(?pandStatus),'">',str(?pandStatusLabel),'</a></li></ul>'
    ) as ?pandWktLabel)
}
