prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix wd: <http://www.wikidata.org/entity/>
prefix wdt: <http://www.wikidata.org/prop/direct/>
select ?shape ?shapeLabel {
  ?windfarm wdt:P31 wd:Q194356 ; # windfarm
            wdt:P17 wd:Q55 ; # Netherlands
            wdt:P625 ?shape ;
            rdfs:label ?label .
  bind(concat(
    '<img src="https://wiki.openstreetmap.org/w/images/0/0c/Power-wind-16.svg">',
    '<a href="',str(?windfarm),'">',str(?label),'</a>') as ?shapeLabel)
}
limit 100
