PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX schema: <http://schema.org/>
PREFIX hg: <http://rdf.histograph.io/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX bag: <http://bag.basisregistraties.overheid.nl/def/bag#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX naa:	<http://archief.nl/def/>

SELECT ?plaatsnaamObject (count(?tradeaction) AS ?numVerkochtePanden) (count(?transactieObjectInPlaats) AS ?numKopersInPlaats) (count(?transactieObjectBuitenPlaats) AS ?numKopersBuitenPlaats) (xsd:integer(sum(?prijsObject)/100000) AS ?totWaarde_x100K) WHERE 
{
  		{
    		?tradeaction a schema:TradeAction ;
                 schema:object/dct:type hg:Building ;
                 schema:object/vcard:hasAddress/vcard:locality ?plaatsnaamObject ;
    			 naa:sellingPrice ?prijsObject .
  		}
  		UNION
		{
		    ?transactieObjectInPlaats a schema:TradeAction ;
                 schema:object/dct:type hg:Building ;
                 schema:buyer/vcard:hasAddress/vcard:locality ?plaatsnaamObject . 

		}
    	UNION
		{
		    ?transactieObjectBuitenPlaats a schema:TradeAction ;
                 schema:object/dct:type hg:Building ;
                 schema:object/vcard:hasAddress/vcard:locality ?plaatsnaamObject ;
                 schema:buyer/vcard:hasAddress/vcard:locality ?plaatsnaamKoperObject . 
    
    		filter (?plaatsnaamObject != ?plaatsnaamKoperObject)
		}
  
} 
GROUPBY ?plaatsnaamObject
ORDERBY desc(?numVerkochtePanden)
OFFSET 0
LIMIT 20
