PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX schema: <http://schema.org/>
PREFIX bag: <http://bag.basisregistraties.overheid.nl/def/bag#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX naa:	<http://archief.nl/def/>

SELECT ?koper (xsd:integer(sum(?prijsObject)/100000) AS ?totaal_waarde_100K) (count(?transactie) AS ?transacties) WHERE {
 
	?transactie a schema:TradeAction;	
             naa:sellingPrice ?prijsObject;
             schema:buyer ?koperURI.	
    ?koperURI skos:prefLabel ?koper;
    FILTER(?koper != "")      

} 
GROUPBY ?koper
ORDERBY desc(?totaal_waarde_100K)
LIMIT 25
