PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX gwsw: <http://data.gwsw.nl/1.4/totaal/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX brt: <http://brt.basisregistraties.overheid.nl/def/top10nl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX bag: <http://bag.basisregistraties.overheid.nl/def/bag#>
PREFIX pdok: <http://data.pdok.nl/def/pdok#>
PREFIX cbs: <http://betalinkeddata.cbs.nl/def/cbs#>

SELECT ?buurt ?wkt ?wktLabel WHERE {
  SERVICE <http://sparql.gwsw.nl/repositories/TestVali> {
      ?rg a gwsw:Rioleringsgebied ;
          rdfs:label ?rg_naam ;
          gwsw:hasAspect ?ori .
      ?ori a gwsw:Gebiedsorientatie ;
           gwsw:hasAspect ?bg .
      ?bg a gwsw:Buitengrens ;
          gwsw:hasValue ?gml .
      filter(contains(?rg_naam, "pancras"))
  }


  {
    ?buurt a cbs:Buurt;
           rdfs:label ?buurt_label ;
           geo:hasGeometry ?geom ;
           ?within ?wijk .
    ?wijk a cbs:Wijk;
           ?within ?cbs_gemeente .
    ?cbs_gemeente rdfs:label "Langedijk"@nl .
  } UNION {
    ?buurt a cbs:Buurt;
           rdfs:label ?buurt_label ;
           geo:hasGeometry ?geom ;
           ?within ?wijk .
    ?wijk a cbs:Wijk;
           ?within ?cbs_gemeente .
    ?cbs_gemeente rdfs:label "Alkmaar"@nl .
  }

  ?geom geo:asWKT ?wkt ;
        pdok:asWKT-RD ?wkt_rd .

  filter(geof:sfIntersects(?wkt_rd, ?gml))
  bind(concat("<a href='", str(?buurt), "' target='_blank'><h2>", str(?buurt_label), "</h2></a>") as ?wktLabel)

}
