prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rvo: <https://data.labs.pdok.nl/rvo/def/>
select ?shape ?shapeLabel
FROM <https://data.labs.pdok.nl/dataset/rvo>
{
  ?land a rvo:Land ;
    rdfs:label ?naam ;
    geo:hasGeometry/geo:asWKT ?shape ;
    rvo:vlag ?url .
  bind(concat('<h2>',str(?naam),'</h2></a>',
      '<img src="',str(?url),'" width="300">') as ?shapeLabel)
  FILTER langMatches( lang(?naam), "NL" )
}
