prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rvo: <https://data.labs.pdok.nl/rvo/def/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
select ?naam (xsd:integer(?bbp) as ?bbp_usd) {
  ?land a rvo:Land ;
    rvo:bbp ?bbp ;
    rdfs:label ?naam
}
