prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rvo: <https://data.labs.pdok.nl/rvo/def/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
select ?naam ?bbp_usd
FROM <https://data.labs.pdok.nl/dataset/rvo>
{
  ?land a rvo:Land ;
    rvo:bbp ?bbp ;
    rdfs:label ?naam .
      FILTER langMatches( lang(?naam), "NL" )
    BIND(STRDT(STR(?bbp), xsd:integer) AS ?bbp_usd)
}
