prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rvo: <https://data.labs.pdok.nl/rvo/def/>
select ?taal (count(?naam) as ?n) (group_concat(?naam; separator=', ') as ?landen)
FROM <https://data.labs.pdok.nl/dataset/rvo>
{
  ?land a rvo:Land ;
    rdfs:label ?naam ;
    rvo:taal ?taal.
      FILTER langMatches( lang(?naam), "NL" )
}
group by ?taal
order by desc(?n)
