prefix bag: <http://bag.basisregistraties.overheid.nl/def/bag#>
prefix brk: <http://brk.basisregistraties.overheid.nl/def/brk#>
prefix dct: <http://purl.org/dc/terms/>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select * {
  bind('Oranjekade'@nl as ?straatNaam)
  ?nummeraanduiding
    bag:bijbehorendeOpenbareRuimte/rdfs:label ?straatNaam;
    bag:huisnummer ?huisnummer;
    bag:postcode ?postcode.
  filter(strstarts(?postcode,'2011'))
  service <https://data.labs.pdok.nl/sparql> {
    # TBD: Dit komt uit de Default Graph.
    ?nummeraanduiding dct:related ?perceel.
  }
  ?perceel
    a brk:Perceel;
    brk:begrenzingPerceel/geo:asWKT ?perceelShape;
    brk:perceelnummer ?perceelnummer.
  bind('''
    <h1>
      <a href="{{nummeraanduiding}}" target="_blank" noreferrer>
        {{straatNaam}} {{huisnummer}}
      </a>
    </h1>
    <p>
      <a href="{{perceel}}" target="_blank" noreferrer>
        Perceel: {{perceelnummer}}
      </a>
    </p>
  ''' as ?perceelShapeLabel)
}
limit 50
