cbs:werkgelegenheid_aantalbanen_B_Fnijverheidenenergie_Binnen10km_x1000
cbs:werkgelegenheid_aantalbanen_Alandbouw_bosbouwenvisserij_Binnen10km_x1000  
cbs:werkgelegenheid_aantalbanen_A_Ualleeconomischeactiviteiten_Binnen10km_x1000

cbs:werkgelegenheid_aantalbanen_O_Uniet_commerciëledienstverlening_Binnen10km_x1000
cbs:werkgelegenheid_aantalbanen_G_Ncommerciëledienstverlening_Binnen10km_x1000
