prefix cbs: <https://data.pdok.nl/cbs/vocab/>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
select ?wkt ?wktColor ?wktLabel {
  ?gemeente a cbs:Gemeente ;
            geo:hasGeometry/geo:asWKT ?wkt ;
            rdfs:label ?label .
  graph <https://data.pdok.nl/cbs/energiebesparingspotentie_gemeente> {
    ?gemeente cbs:gemiddeldeTheoretischeBesparingspotentieInEuroPerJaar_populatie ?euro
  }
  bind(xsd:float(?euro - 25) / 1900 as ?normalized)
  bind(concat("jet,",str(?normalized)) as ?wktColor)
  #bind(concat('<h3>',?label,'</h3><p>€',str(?euro),',-</p>') as ?wktLabel)
}
limit 400
