# Landelijke gemiddeldes voor afstanden tot voorzieningen.
prefix dct: <http://purl.org/dc/terms/>
prefix cbs: <https://data.pdok.nl/cbs/vocab/>
select
  (avg(?_oprit) as ?oprit)
  (avg(?_trein) as ?trein)
  (avg(?_kind) as ?kind)
  (avg(?_boodschap) as ?boodschap)
  (avg(?_auto) as ?auto)
  (avg(?_arbeid) as ?arbeid)
{
  ?gemeente a cbs:Gemeente ;
    dct:partOf [] ;
    cbs:verkeerenvervoer_Afstandtotoprithoofdverkeersweg_km ?_oprit ;
    cbs:verkeerenvervoer_Treinstations_Afstandtottreinstationstotaal_km ?_trein ;
    cbs:kinderopvang_Kinderdagverblijf_Afstandtotkinderdagverblijf_km ?_kind ;
    cbs:detailhandel_Winkelsdagelijkseboodschappen_Afstandtotov.dagel.levensmiddelen_km ?_boodschap ;
    cbs:motorvoertuigen_Personenauto_s_Personenauto_sperhuishouden_perhuishouden ?_auto ;
    cbs:nettoarbeidsparticipatie_p ?arbeid .
}
