prefix bag: <http://bag.basisregistraties.overheid.nl/def/bag#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix geof: <http://www.opengis.net/def/function/geosparql/>
prefix nwbw: <http://data.labs.pdok.nl/nwb-wegen/def/nwb-wegen#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix uom: <http://www.opengis.net/def/uom/OGC/1.0/>
prefix verblijfsobject: <http://bag.basisregistraties.overheid.nl/bag/id/verblijfsobject/>
select * {
  {
    service <https://data.pdok.nl/sparql> {
      select distinct ?vbo ?wkt ?wktLabel ?afstand {
        {
          ?vbo a ?type ;
               bag:pandrelatering ?pand ;
               geo:hasGeometry/geo:asWKT ?wkt ;
               rdfs:label ?vboLabel .
          ?pand rdfs:label ?pandLabel .
          filter(?vbo = verblijfsobject:0307010000462567)
          bind(concat(
            '<h3>Coffeeshop</h3>',
            '<p><a href="',str(?pand),'">',str(?pandLabel),'</a><br>',
            '<a href="',str(?vbo),'">',str(?vboLabel),'</a></p>'
            ) as ?wktLabel)
        } union {
          ?vbo a ?type ;
               bag:pandrelatering ?pand ;
               geo:hasGeometry/geo:asWKT ?wkt ;
               rdfs:label ?vboLabel .
          ?pand rdfs:label ?pandLabel .
          filter(?vbo = verblijfsobject:0307010000519401)
          bind(concat(
            '<h3>School</h3>',
            '<p><a href="',str(?pand),'">',str(?pandLabel),'</a><br>',
            '<a href="',str(?vbo),'">',str(?vboLabel),'</a></p>'
            ) as ?wktLabel) .
          bind( ?wkt as ?punt2) .
        }
      }
    }
  } union {
    select * {
      ?wegvak a nwbw:Wegvak ;
              geo:hasGeometry/geo:asWKT ?wkt ;
              rdfs:label ?wegvaklabel .
      bind(geof:distance(?punt2, ?wkt, uom:metre) as ?afstand) .
      bind(concat(
        '<h3>Wegvak</h3>',
        '<p><a href="',str(?wegvak),'">',str(?wegvaklabel),'</a></p>'
        ) as ?wktLabel)
    }
    order by ?afstand
    limit 1
  }
}
