PREFIX brt: <http://brt.basisregistraties.overheid.nl/def/top10nl#>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix schema: <http://schema.org/>

select ?shape (sample(?shapeLabel) as ?shapeLabel) {
  {
    select ?gemeenteNaam1 ?shape {
      ?gemeente a brt:Gemeente;
        geo:hasGeometry ?geo1;
        rdfs:label ?gemeenteNaam1.
      ?geo1 geo:asWKT ?shape.

    }
  }
    ?image schema:contentLocation ?gemeenteNaam1;
      dc:description ?description;
          schema:thumbnail ?url.
}
  bind(concat(
    '<h3>',?gemeenteNaam1,'</h3>',
    '<img width="250" src="',?url,'">',
    '<p>',?description,'</p>') as ?shapeLabel)
}
group by ?shape
limit 100
