PREFIX brt: <http://brt.basisregistraties.overheid.nl/def/top10nl#>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix schema: <http://schema.org/>
prefix bag: <http://bag.basisregistraties.overheid.nl/def/bag#>

select ?shape (sample(?shapeLabel) as ?shapeLabel)
WHERE{
      service <https://data.pdok.nl/sparql> {
      ?class a bag:Woonplaats;
       rdfs:label ?gemeenteNaam1;
       bag:geometrieWoonplaats ?geo1.
       ?geo1 geo:asWKT ?shape.

    }
  }
  ?image
    dce:description ?description;
    schema:contentLocation/schema:name ?gemeenteNaam2;
    schema:thumbnail ?url.
}
group by ?shape
limit 100
