prefix dce: <http://purl.org/dc/elements/1.1/>
prefix schema: <http://schema.org/>
select ?subject (count(?image) as ?n) {
  ?image a schema:Photograph;
         dce:subject ?subject.
}
group by ?subject
order by desc(?n)
limit 20
