prefix brt: <http://brt.basisregistraties.overheid.nl/def/top10nl#>
prefix cbs: <https://data.pdok.nl/cbs/def/>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
select ?wkt ?wktLabel {
  bind ("GM0200" as ?gemeenteCode)
  graph <https://data.pdok.nl/cbs/2015> {
    ?buurt2015 cbs:GM_CODE ?gemeenteCode ;
               cbs:BU_CODE [] ;
               cbs:WK_CODE [] ;
               cbs:AF_CAFE ?cafe2015 ;
               cbs:BU_NAAM ?buurtNaam ;
               geo:hasGeometry/geo:asWKT ?wkt
  }
  graph <https://data.pdok.nl/cbs/2014> {
    ?buurt2014 cbs:GM_CODE ?gemeenteCode ;
               cbs:BU_CODE [] ;
               cbs:WK_CODE [] ;
               cbs:AF_CAFE ?cafe2014
  }
  graph <https://data.pdok.nl/cbs/2013> {
    ?buurt2013 cbs:GM_CODE ?gemeenteCode ;
               cbs:BU_CODE [] ;
               cbs:WK_CODE [] ;
               cbs:AF_CAFE ?cafe2013
  }
  graph <https://data.pdok.nl/cbs/2012> {
    ?buurt2012 cbs:GM_CODE ?gemeenteCode ;
               cbs:BU_CODE [] ;
               cbs:WK_CODE [] ;
               cbs:AF_CAFE ?cafe2012
  }
  bind (concat('<p><b>Afstrand tot café<br>',
    str(?buurtNaam),'</b></p>',
    '<p>2012: ',str(?cafe2012),' km<br>',
    '2013: ',str(?cafe2013),' km<br>',
    '2014: ',str(?cafe2014),' km<br>',
    '2015: ',str(?cafe2015),' km</p>'
    ) as ?wktLabel)
}
limit 200
