prefix bag: <http://bag.basisregistraties.overheid.nl/def/bag#>
prefix bag_beg: <http://bag.basisregistraties.overheid.nl/id/begrip/>
prefix begrip: <http://bgt.basisregistraties.overheid.nl/bgt/id/begrip/>
prefix bgt: <http://bgt.basisregistraties.overheid.nl/def/bgt#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select (count(?bag_pand) as ?count) {
  ?verblijfsobject
    bag:hoofdadres/bag:bijbehorendeOpenbareRuimte/bag:bijbehorendeWoonplaats <http://bag.basisregistraties.overheid.nl/bag/id/woonplaats/1270> ;
    bag:pandrelatering ?bag_pand .

  graph ?voorkomen {
    ?bag_pand a bag:Pand .
    #    ?bag_pand bag:status ?status .
    #    filter(?status = bag_beg:PandInGebruik || ?status = bag_beg:PandInGebruik_nietIngemeten)
  }
  filter not exists {
    ?voorkomen bag:eindGeldigheid ?eind .
  }
}
