prefix kvk: <http://data.labs.pdok.nl/kvk/def/>
prefix schema: <http://schema.org/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
select ?sbi (sum(?werknemers) as ?n) {
  graph <http://data.labs.pdok.nl/graph/kvk> {
    ?organizatie kvk:plaats "Zwolle"^^xsd:string ;
                 kvk:sbiOmschrijving ?sbi ;
                 schema:numberOfEmployees ?werknemers .
  }
}
group by ?sbi
order by desc(?n)
limit 10
