prefix bag: <http://bag.basisregistraties.overheid.nl/def/bag#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix pand: <http://bag.basisregistraties.overheid.nl/bag/id/pand/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select ?shape ?shapeLabel {
  values ?pand { pand:0363100012085435 }
  ?nummeraanduiding a bag:Nummeraanduiding ;
                    bag:postcode ?postcode ;
                    bag:huisnummer ?huisnummer ;
                    bag:bijbehorendeOpenbareRuimte ?openbareRuimte .
  ?verblijfsobject a/rdfs:label ?verblijfsobjectType ;
                   bag:hoofdadres ?nummeraanduiding ;
                   bag:pandrelatering ?pand ;
                   geo:hasGeometry/geo:asWKT ?shape .
  ?openbareRuimte bag:naamOpenbareRuimte ?naamOpenbareRuimte .
  bind(concat(
    '<strong>',sample(?naamOpenbareRuimte),' ',sample(str(?huisnummer)),', ',sample(?postcode),'</strong><br>',
    group_concat(distinct ?verblijfsobjectType;separator='<br>')) as ?shapeLabel)
}
group by ?shape
