prefix bag: <http://bag.basisregistraties.overheid.nl/def/bag#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
select ?shape {
  ?nummeraanduiding a bag:Nummeraanduiding ;
                    bag:bijbehorendeOpenbareRuimte ?openbareruimte ;
                    bag:huisnummer 300 ;
                    bag:postcode "1068LE" .
  ?verblijfsobject bag:hoofdadres ?nummeraanduiding ;
                   bag:pandrelatering ?Pand .
  ?openbareruimte bag:bijbehorendeWoonplaats ?woonplaats .
  {
    ?verblijfsobject geo:hasGeometry/geo:asWKT ?shape .
  } union {
    ?pand geo:hasGeometry/geo:asWKT ?shape .
  } union {
    ?woonplaats geo:hasGeometry/geo:asWKT ?shape .
  }
}
